version: '2'

services:

  db:
    image: mysql
    ports:
    - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: baldadb
      MYSQL_USER: balda
      MYSQL_PASSWORD: balda
    volumes:
    - ./mysql:/var/lib/mysql
    restart: always

  balda:
    build: .
    working_dir: /code/src/github.com/BaldaGo/balda-go
    depends_on:
    - db
    volumes:
    - ./:/code/src/github.com/BaldaGo/balda-go
    environment:
    - DEBUG=1
    ports:
    - "8888:8888"
    command: ./balda-go
    restart: always
